
version: "1"
rules:
  - base: main
    upstream: cabishop:main
    mergeMethod: merge
    reviewers:
      - cabishop
      - hannahgooden
    assignees:
      - cabishop
      - hannahgooden
env:
  - PULL_INTERVAL: 60
